name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: archlinux
      options: --privileged
    
    steps:
    - name: Build Arch Linux package
      uses: FFY00/build-arch-package@v1
      with:
        PKGBUILD: PKGBUILD
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: $HOME/arch-packages
